# ===========================
# Training
# ===========================
checkpoint_path: './checkpoints/flowers'
max_checkpoints_to_keep: 200
max_num_images_kimg: 4000
checkpoint_intervall_kimg: 1
log_dir: './logs/flowers'
log_metrics_intervall_kimg: 1
dlatent_avg_beta: 0.95
print_metrics_intervall_kimg: 1
label_conditioning: False
shuffle_buffer_size: 25000
gamma: 100
disc_reg_intervall: 2

# ===========================
# Generation
# ===========================

truncation_psi: 0.6
truncation_cutoff: 200

# ===========================
# Inputs
# ===========================
num_channels: 3
resolution: 128
batch_size: 4
labels_size: 0

# ===========================
# Mapping Network
# ===========================
latent_size: 128
hidden_size: 128
dlatent_size: 128
num_dense_layers: 4
alpha: 0.2
lr_multiplier: 0.01
normalize_latents: True

# ===========================
# Synthesis Network
# ===========================

feature_maps_base: 1024
feature_maps_decay: 1.0
feature_maps_min: 1 
feature_maps_max: 512

# ===========================
# Discriminator
# ===========================

minibatch_std_group_size: 4
minibatch_std_n_features: 1

# ===========================
# Optimizer 
# ===========================
discriminator_base_learning_rate: 0.004
discriminator_beta_1: 0.0
discriminator_beta_2: 0.99
discriminator_epsilon: 1e-8
generator_base_learning_rate: 0.004
generator_beta_1: 0.0
generator_beta_2: 0.99
generator_epsilon: 1e-8